sync:
  toHost:
    ingresses:
      enabled: true
    persistentVolumeClaims:
      enabled: true
    services:
      enabled: true
  fromHost:
    nodes:
      enabled: true

integrations:
  metricsServer:
    enabled: true
    nodes: true
    pods: true
    apiService:
      service:
        name: metrics-server
        namespace: kube-system
        port: 443

exportKubeConfig:
  context: vcluster-app-a